# Generated by Django 5.1.4 on 2024-12-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnc',
            fields=[
                ('cnc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cnc_link', models.CharField(max_length=70)),
                ('cnc_desc', models.TextField()),
                ('cnc_price', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'db_table': 'cnc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=100, null=True)),
                ('definicion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diccionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('categoria_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lcapitulos',
            fields=[
                ('c_idcapitulo', models.BigAutoField(db_column='C_IdCapitulo', primary_key=True, serialize=False)),
                ('c_capitulo_desc', models.IntegerField(blank=True, db_column='C_Capitulo_Desc', null=True)),
            ],
            options={
                'db_table': 'lcapitulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('indice', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('st_am', models.IntegerField()),
                ('end_am', models.IntegerField()),
                ('st_pm', models.IntegerField()),
                ('end_pm', models.IntegerField()),
            ],
            options={
                'db_table': 'lectura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llibros',
            fields=[
                ('l_idlibro', models.BigAutoField(db_column='L_IdLibro', primary_key=True, serialize=False)),
                ('l_link', models.CharField(blank=True, db_column='L_link', max_length=150, null=True)),
                ('l_book', models.CharField(blank=True, db_column='L_book', max_length=150, null=True)),
                ('l_libro_desc', models.CharField(blank=True, db_column='L_Libro_Desc', max_length=100, null=True)),
            ],
            options={
                'db_table': 'llibros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ltema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_titulo', models.TextField(blank=True, db_column='T_titulo', null=True)),
                ('t_id_verso_start', models.IntegerField(blank=True, db_column='T_id_verso_start', null=True)),
                ('t_id_verso_end', models.IntegerField(blank=True, db_column='T_id_verso_end', null=True)),
            ],
            options={
                'db_table': 'ltema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lversiculos',
            fields=[
                ('v_idversiculo', models.BigAutoField(db_column='V_IdVersiculo', primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lversiculos',
                'managed': False,
            },
        ),
    ]
