# Generated by Django 5.1.4 on 2024-12-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luzapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cnc',
        ),
        migrations.DeleteModel(
            name='Diccionario',
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
        migrations.DeleteModel(
            name='Lectura',
        ),
        migrations.DeleteModel(
            name='Ltema',
        ),
    ]
